# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        :title
#relative_permalinks: true

# Setup
title:            kyRobot
tagline:          'Kyle'
description:      'Musings of a Software Engineering, App developing, borderline nerd'
url:              http://www.kyrobot.com
baseurl:          /

author:
  name:     "Kyle Milner"
  github:   "kyrobot"
  twitter:  "fteem"
  linkedin: "kylemilner"

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kyRobot

gems:
  - jekyll-paginate